### ISSUE TITLE
sndfile-waveform: 6-channel input => Channel 6 missing from generated PNG

### ISSUE THREAD

**Issue by wolfgangw** [erikd/sndfile-tools#20]
Hi Erik,

sndfile-waveform apparently drops channel 6 from a 6-channel input audiofile, at least from the ones I've been throwing at it (24 bps, 48 kHz).

The command I've used:

```bash
sndfile-waveform -c -1 -l -g 1280x980 <input> <output>
```

See https://github.com/wolfgangw/blobs/tree/master/sndfile-waveform-material to reproduce. The 6-channel audiofile contains -- in temporal sequence -- 1 tone per channel in center (ch 3), left (ch 1), right (ch 2), left surround (ch 5), right surround (ch 6) and LFE (ch 4).

**Comment by erikd** [comment]
Fixed in the above commit.
