### ISSUE TITLE
Strange florets in sndfile-spectrogram output

### ISSUE THREAD

**Issue by martinwguy** [erikd/sndfile-tools#28]
Chasing down some strange artifacts in sndfile-spectrogram's output for real music, I've made a simple example that exhibits the same artifacts, visible at the start and end of a 1-second 60Hz tone burst
http://martinwguy.co.uk/test/60Hz.wav
sndfile-spectrogram --no-border 60Hz.wav 400 8192 60Hz-kaiser.png
The following image is a 4x magnification of the bottom of the output
![60hz-kaiser-detail-x4](https://cloud.githubusercontent.com/assets/608929/11691318/c45922fe-9e9a-11e5-8549-8eaedf19fc70.png)
At normal screen resolution, these florets recede into visual imperceptibility but when applying an external log-frequency-axis wrapper to the output they are very visible at lower frequencies of the musical range.

I assume it is also this artifact that is causing the apparent tremolo in the constant tone.
Audacity on the same input file gives a dead-level line at the same FFT size and magnification.

Hypothesis: It's an artifact of our windowing function
Experiment: Try the same transform with --nuttall and see if it changes
Observation: With the other windowing functions, the output exhibits the same artifacts
with --nuttall
![60hz-nuttall-detail-x4](https://cloud.githubusercontent.com/assets/608929/11691681/67be24b6-9e9c-11e5-9551-9a6b4919846f.png)
with --hanning
![60hz-hanning-detail-x4](https://cloud.githubusercontent.com/assets/608929/11691816/0ea9cd34-9e9d-11e5-9e2a-337b4dd631b5.png)
Rejected: It's not the windowing function.

**Comment by martinwguy** [comment]
Observation: The height of each floret is half the pixels-per-second value.
The above analyse 2-second sample into 400 width, giving 200 pixels per second. The tone is as 60Hz and the height of each floret is at 100Hz.

Observation: Increasing the width (increasing pixels per second) increases the height of the florets proportionally. Here at 240pps the florets are 120Hz high.
![60hz-hanning-240pps-detail-x4](https://cloud.githubusercontent.com/assets/608929/11692405/96ccda88-9e9f-11e5-8131-72a881842d7a.png)

**Comment by erikd** [comment]
I think these are pretty cool, and I've seen lots of spectrograms with artifacts like these.

**Comment by martinwguy** [comment]
Funny and pretty, yes.

I've put "sox spectrogram" in as an optional replacement for
sndfile-spectrogram in my script.
The quality of the result is completely another thing. Smooth and
without random garbage.
Unfortunately it had the usual arbitrary limits on output size (which
I have removed) but is INCREDIBLY SLOW. Where sndfile-spectrogram
finished in 45 seconds, sox, after half an hour, is still grinding,
which makes it at least 40 times slower. This makes the difference
between me being able to proceed with what I am tryng to do, or dying
before I can do anything.

So for the moment sndfile-spectrogram is the best tool, but only for
practical reasons, not for the quality of its output. If you don't
want me to try to find out why it is doing this and trying to fix it,
just let me know. I won't bother you again!

    M

**Comment by erikd** [comment]
Happy to have you fix this if you can but unfortunatley I'm not able to offer much in the way of time and effort here. Currently way too busy with worked related stuff.

**Comment by martinwguy** [comment]
When the samples are read from the audio file to produce a column of pixels, the time point around which they are read is truncated to an integer value, the starting sample number. As the time distance between adjacent pixel columns is not necessarily an exact number of samples, this effectively introduces a time jitter of up to one sample period. We could mitigate this be interpolating between samples.

Hypothesis: Time jitter of up to one sample due to starting moment quantization is causing this effect.
Experiment: Interpolate linearly between samples to compensate for the time offset, and see if this improves the output.
Experimental patch: 2cf830bc0befaeee8c389901ab9a3029cf35d202
Observation: At width 400, the output files are identical because the error is always 0 . At width 413, the output files are not identical, but they look just the same.
sndfile-spectrogram --no-border 60Hz.wav 413 8192 60Hz-kaiser-413-8192.png
![60hz-kaiser-413-8192-detail-4x](https://cloud.githubusercontent.com/assets/608929/11762799/5dc4fe22-a0f3-11e5-96b9-e0d00bb014c6.png)
sndfile-spectrogram --no-border --precise 60Hz.wav 413 8192 60Hz-kaiser-413-8192.png
![60hz-kaiser-413-8192-precise-detail-4x](https://cloud.githubusercontent.com/assets/608929/11762800/62893626-a0f3-11e5-85b6-cf45d66b6a0c.png)

Conclusion: The florets are not due to quantization of time to a sample boundary.

**Comment by erikd** [comment]
I wonder if these florets are due to the side lobes of the window functions. If you look at say the Nuttall window, https://en.wikipedia.org/wiki/Window_function#Blackman.E2.80.93Nuttall_window the largest  side lobes are at about -98dB. If you choose the Nuttall window and a synamic range of 95dB do these florets disappear?

**Comment by martinwguy** [comment]
sndfile-spectrogram --dyn-range=95 --no-border --nuttall \
     60Hz.wav 413 8192 60Hz-nuttall-413-8192-dyn95.png
![60hz-nuttall-413-8192-dyn95-detail-x4](https://cloud.githubusercontent.com/assets/608929/11763706/54de2b86-a115-11e5-8d1f-3082a62be146.png)
Nope. Still there.

**Comment by martinwguy** [comment]
Hypothesis: It's caused by the scaling of the Y axis from speclen to height
Rejected: speclen == height in the 8192-high examples, so no interpolation is done in them yet the effect persists.

**Comment by martinwguy** [comment]
Got it. The calculation of magnitudes from the real and complex values in FFTW's "half complex" output format was out by one in the complex part, so mag[1] = sqrt(re[1] * re[1] + im[2] * im[2]) and so on. Here's detail of the first graph with comit 53de8b78e79ff178d0302fe80c66a12f3754b32a
![60hz-detail-x4](https://cloud.githubusercontent.com/assets/608929/11768758/b2f462a0-a1d6-11e5-871e-7158f108b76f.png)

**Comment by erikd** [comment]
Oh, well done! Suppose this can be closed now.
