### ISSUE TITLE
spectrogram labels are sometimes odd

### ISSUE THREAD

**Issue by martinwguy** [erikd/sndfile-tools#35]
The tick-positioning and numbering system sometimes does strange things.
Here are three of them:

With --dyn-range=190 it gives an extra label below the bottom of the heat map legend
Similarly, with maximum frequency == 19000, an extra -20000 is displayed above the graph

With maximum frequency == 13000Hz it labels 0, 2167, 4333, 6500, 8667, 10833 and 13000
Similarly bizzarre sequences are seen at maxfreq of 15000 and 17000.

On a 53.8-second sound file, it there should be another label (50) but the Time labelling is truncated.

    sndfile-generate-chirp -from 0 -to 13000 -linear 26000 53.8 chirp.wav
    sndfile-spectrogram --dyn-range=190 chirp.wav 640 480 chirp.png

![chirp](https://cloud.githubusercontent.com/assets/608929/13203656/1865083e-d8bd-11e5-8075-f923ff8b5c83.png)

The function in question is src/spectrogram.c::calculate_ticks()

**Comment by martinwguy** [comment]
calculate_ticks() is foul, starting with a mysterious table:

    static inline int
    calculate_ticks (double max, double distance, TICKS * ticks)
    {       const int div_array [] =
            {       10, 10, 8, 6, 8, 10, 6, 7, 8, 9, 10, 11, 12, 12, 7, 14, 8, 8, 9
                    } ;
out of which it picks a value by an equally mysterious algorithm, apparently to be used as the number of segments into which to divide the axis with ticks.

Even Erik no longer remembers where this magic table came from and this will also need hacking for te forthcoming log-freq, so it's probably easier to figure out what it should do and rewrite it accordingly with a mind to log-freq's needs.

Net lore says to follow the "1,2,5 rule", which says to make the least significant changing digit of successive numbered labels should change by 1, by 2 or by 5 (passing through 0, obviously!).

There is also written that "labelling every tick makes the axes overcrowded and difficult to follow".
"sox spectrogram" does this, labelling every tick, and it's true.

The current code usually outputs numbers whose least significant changing digit goes 0,2,4,6,8 with ticks at the odd positions in between. It sometimes outputs 0, 1000, 2000 with ticks at the '500 points, or 0, 500, 1000, 1500, 2000 with ticks at 250, 750 and so on, i.e. it implements the 1-2-5 rule adding an unnumbered tick between elements.

It also differs from conventional graph labelling conventions in that prints 0.8, 0.9, 1, 1.1 whereas coventional use seems to be to use 1.0. Personally, I find "1" clearer as it visually marks the unit boundary without making me peer at the little digits.

**Comment by erikd** [comment]
Its pretty safe to bet that the `calculate_ticks()` function was arrived at by some ad-hoc experimental method on a limited number of test cases available at the time.

Pretty sure its time to replace it with something better.
