### ISSUE TITLE
Fix out-of-bounds access

### ISSUE THREAD

**Issue by erikd** [erikd/sndfile-tools#37]
@martinwguy 

As requested in https://github.com/erikd/sndfile-tools/commit/91a704102f08909dbbe8b6326c9cac5de9801035#commitcomment-16300005

Pull the current HEAD, revert commit https://github.com/erikd/sndfile-tools/commit/91a704102f08909dbbe8b6326c9cac5de9801035 and then configure and build with:

    CFLAGS="-g -fsanitize=address" CXXFLAGS=$CFLAGS ./configure
    make clean all check

And you should get a big ASAN dump from the `sndfile-sprectrogram` test.

You ony need to worry about the out-of-bounds errors (with 91a704102f08909d reverted). ASAN also errors out on memory leaks which are not in `sndfile-spectrogram` but in libraries like libfontconfig.

**Comment by martinwguy** [comment]
I think 6ac4ecb08 fixes this

**Comment by erikd** [comment]
Yep, this can be closed.
