### ISSUE TITLE
Horizontal comb of shadows in what should be smooth spectrogram output

### ISSUE THREAD

**Issue by martinwguy** [erikd/sndfile-tools#39]
sndfile-generate-chirp -from 0 -to 500 1000 1 chirp1000.wav
    sndfile-spectrogram --no-border chirp1000.wav 640 501 chirp501.png
generates the following figure. There seem to be single-pixel dark lines and patterns in the borders of the main white/yellow area centre-right and centre-top.

The effect is much the same with linear and logarithmic frequency axes. This is the linear one:
![chirp501](https://cloud.githubusercontent.com/assets/608929/13375493/58278864-dda1-11e5-976f-d65ec8dbbaef.png)

**Comment by martinwguy** [comment]
Hypothesis: It's an artifact of the window function.
Experiment: try different window functions.

Hypothesis: It's caused by interference effects due to the temporal inaccuracy (noise) caused by a window that should be at, say, 1234.5 samples getting the sound at 1234.0 samples.
Experiment: Make the time sampling exact by interpolating between the two samples between which the desired sample value falls and see if this makes any difference.

**Comment by martinwguy** [comment]
Experiment: try different window functions. The original uses the default kaiser window.

Rectangular:
    bin/sndfile-spectrogram --no-border --rectangular --dyn-range=90 chirp1000.wav 640 501 chirp501-rect.png
![chirp501-rect](https://cloud.githubusercontent.com/assets/608929/13379174/0e1ea102-de1f-11e5-8bca-f037dac4e9e2.png)
Nuttall:
![chirp501-nuttall](https://cloud.githubusercontent.com/assets/608929/13379185/604da1d0-de1f-11e5-9f82-63943e03a09b.png)
Hann:
![chirp501-hann](https://cloud.githubusercontent.com/assets/608929/13379187/6db65e20-de1f-11e5-97e7-a70d9a353f39.png)

Observation: They all have more of less similar artifacts.
Conclusion: Either it's not the window function's fault, or all the window functions give artifacts.

**Comment by martinwguy** [comment]
Experiment: Make the time sampling exact by interpolating between the two sample
s between which the desired sample value falls and see if this makes any differe
nce.
Code: http://martinwguy.co.uk/martin/test/sndfile-spectrogram-exact-timing.patch

Results:
Default(kaiser):
![chirp501-kaiser](https://cloud.githubusercontent.com/assets/608929/13379609/8aec70d2-de2a-11e5-84f0-c0226df60678.png)

Nuttall:
![chirp501-nuttall](https://cloud.githubusercontent.com/assets/608929/13379614/b35c7a9e-de2a-11e5-852f-533e37578dc8.png)

Hann:
![chirp501-hann](https://cloud.githubusercontent.com/assets/608929/13379611/94e2d644-de2a-11e5-9107-daa928715628.png)

Rectangular
![chirp501-rect](https://cloud.githubusercontent.com/assets/608929/13379612/997b17de-de2a-11e5-9645-84d2e29836fa.png)

Results: This introduces extra artifacts in the time dimension.

**Comment by martinwguy** [comment]
Hypothesis: The artifacts are caused by the extreme nature of the example (a full-amplitude 0 to 500Hz tone sweep at 1000Hz sample rate
Experiment: Try the same analysis at a sensible sampling rate
    sndfile-generate-chirp  -from 0 -to 24000 48000 1 chirp48k.wav
Results:
Kaiser window:
![chirp48k-kaiser](https://cloud.githubusercontent.com/assets/608929/13379635/42dcf9b4-de2b-11e5-8c12-194b7b017b46.png)

Nuttall:
![chirp48k-nuttall](https://cloud.githubusercontent.com/assets/608929/13379636/472563bc-de2b-11e5-9ba8-f7ec42032d6e.png)

Hann:
![chirp48k-hann](https://cloud.githubusercontent.com/assets/608929/13379638/4b835bc6-de2b-11e5-928e-a12f0d19d638.png)

Rectangular:
![chirp48k-rectangular](https://cloud.githubusercontent.com/assets/608929/13379641/4efb6dfc-de2b-11e5-8c69-83f9088a7e76.png)

Conclusion: The artifacts are caused by a crazy test piece. Graphs with non-extreme data are OK.

**Comment by erikd** [comment]
Cool, thanks for exploring this!

**Comment by martinwguy** [comment]
Glad you enjoyed it :dancer: 
There was an ancillary fix in the patch, which separated out the allocation of the 4 big arrays, instead of allocating (2 + 2 + 2 + 1) * speclen and then calculating offsets into that. It didn't seem to break anything :) Shall I separate that out or u can pick it out of
http://martinwguy.co.uk/test/sndfile-spectrogram-exact-timing.patch

**Comment by erikd** [comment]
Yeah, I pulled the allocation stuff out of that patch and then added the corresponding `free()s`, mainly so that tools like Valgrind and ASAN don't complain.
