### ISSUE TITLE
sndfile-resample in both libsamplerate and sndfile-tools

### ISSUE THREAD

**Issue by SoapGentoo** [erikd/sndfile-tools#53]
Hi @erikd 
We are getting file collisions with the new 1.04 release:
https://bugs.gentoo.org/645258

Which package is the authoritative source on `sndfile-resample`? I guess this should also be fixed in either one of the repos.

**Comment by erikd** [comment]
I wanted to move the `sndfile-resample` from libsamplerate (so I can drop the libsndfile build dependency) to sndfile-tools which relies on a number of different libraries.
