### ISSUE TITLE
Unhelpful sndfile-mix-to-mono behavior when input is mono

### ISSUE THREAD

**Issue by mgrachten** [erikd/sndfile-tools#58]
I'm running into a file logic issue when using sndfile-mix-to-mono in my work flow. What I want to do is convert a set of audio files (possibly stereo, possibly mono) to an all mono set of files. I want to keep the original set of files, that is, stereo files should be converted, and mono files should be copied. I thought this would have been as easy as:

    for fn in *.wav
    do
      sndfile-mix-to-mono $fn ${fn/.wav/_mono.wav}
    done

But this relies on the false assumption that sndfile-mix-to-mono would copy the input file to the output file if it is already mono. Since it does not do that but instead exits prematurely, I thought the following might work:

    for fn in *.wav
    do
      cp $fn ${fn/.wav/_mono.wav}
      sndfile-mix-to-mono $fn ${fn/.wav/_mono.wav}
    done

This relies on the false assumption that sndfile-mix-to-mono would not touch the specified the output file when it does not convert the input file. Instead it deletes the output file, even if it exits prematurely. My third try was:

    for fn in *.wav
    do
      sndfile-mix-to-mono $fn ${fn/.wav/_mono.wav}
      if [ ! $? -eq 0 ]
      then
            cp $fn ${fn/.wav/_mono.wav}
      fi
    done

This relies on the false assumption that sndfile-mix-to-mono would signal that it did not perform the conversion by a non-zero exit value.

Given these assumptions about sndfile-mix-to-mono do not hold, I would need to resort to another tool to inspect if the input file is mono, and only if it is not apply sndfile-mix-to-mono. This is not a big deal of course, but I think in particular the second assumption (sndfile-mix-to-mono does not touch the specified the output file when it does not convert the input file) is a very reasonable one to make, and would make working with sndfile-mix-to-mono easier.

So my proposal would be postpone the deletion of the output file (if it exists) until it is clear that the program will not exit prematurely. I realize changing the behavior of mature and ubiquitous commandline programs is contentious, but then again, the output file deleting behavior is not specified behavior of the program.

**Comment by erikd** [comment]
Can this be closed?

**Comment by mgrachten** [comment]
Yes, thanks a lot!
