### ISSUE TITLE
Debain package outdated?

### ISSUE THREAD

**Issue by ckemere** [erikd/sndfile-tools#61]
The Debian sndfile-tools package seems to be outdated. I found that sndfile-jackplay worked when compiled from source but not with the packaged version.

**Comment by erikd** [comment]
You need to raise that bug with the Debian maintainers. I only maintain the upstream source package.

**Comment by erikd** [comment]
Actually let me make sure what I have in git has actually been released.

**Comment by erikd** [comment]
Version 1.0.4 released: http://www.mega-nerd.com/libsndfile/tools/
